BEGIN;

CREATE TYPE user_status AS ENUM (
    'admin',
    'user',
    'blocked'
);

CREATE TYPE visibility AS ENUM (
    'Public',
    'Private'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT UNIQUE NOT NULL,
    user_password TEXT NOT NULL,
    user_status user_status NOT NULL,
    visibility visibility NOT NULL
);

CREATE TABLE folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    folder_name TEXT NOT NULL
);

CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    note_name TEXT,
    modified TEXT,
    content TEXT
);

COMMIT;