BEGIN;

CREATE TYPE user_status AS ENUM (
    'admin',
    'user',
    'blocked'
);

CREATE TYPE visibility AS ENUM (
    'Public',
    'Private'
);

CREATE TYPE request_status AS ENUM (
    'None',
    'Pending',
    'Approved'
);

CREATE TYPE following_status AS ENUM (
    'True',
    'False'
);

CREATE TYPE blocked_status AS ENUM (
    'True',
    'False'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT UNIQUE NOT NULL,
    user_password TEXT NOT NULL,
    user_status user_status NOT NULL,
    visibility visibility NOT NULL,
    avatar TEXT NOT NULL
);

CREATE TABLE folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    folder_name TEXT NOT NULL
);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    user_name TEXT NOT NULL,
    avatar TEXT NOT NULL,
    folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    post_name TEXT,
    modified TEXT,
    content TEXT,
    visibility visibility NOT NULL
);

CREATE TABLE connections (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    connection_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    connection_name TEXT NOT NULL,
    request request_status NOT NULL,
    is_following following_status NOT NULL,
    is_blocked blocked_status NOT NULL
);

COMMIT;